name: GitHub Actions Build

on: [push, pull_request]

env:
  BASE_BRANCH: master
  MANUAL_ASSET: ags-help.chm
  AUTO_TEST_ASSET_BASENAME: ags3-auto-test
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 20
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows-mingw-x86_64, os: windows-latest,   sys: Windows, gfx: D3D9, artifact: 'ags-mingw-x86_64', shell: 'msys2 {0}', runbin: "./ags",      bindir: "",        cmakecmd: "cmake", msystem: mingw64, msys-env: mingw-w64-x86_64 }
        - { name: Windows-mingw-arm64,  os: windows-11-arm,   sys: Windows, gfx: D3D9, artifact: 'ags-mingw-arm64',  shell: 'msys2 {0}', runbin: "./ags",      bindir: "",        cmakecmd: "cmake", msystem: clangarm64, msys-env: mingw-w64-clang-aarch64 }
        - { name: Windows,              os: windows-latest,   sys: Windows, gfx: D3D9, artifact: 'ags-windows',      shell: cmd,         runbin: ".\\ags.exe", bindir: "Release", cmakecmd: "cmake" }
        - { name: Ubuntu-x86_64,        os: ubuntu-latest,    sys: Ubuntu,  gfx: OGL,  artifact: 'ags-linux-x86_64', shell: sh,          runbin: "./ags",      bindir: "",        cmakecmd: "cmake" }
        - { name: Ubuntu-Arm64,         os: ubuntu-22.04-arm, sys: Ubuntu,  gfx: OGL,  artifact: 'ags-linux-Arm64',  shell: sh,          runbin: "./ags",      bindir: "",        cmakecmd: "cmake" }
        - { name: macOS,                os: macos-latest,     sys: macOS,   gfx: OGL,  artifact: 'ags-macos',        shell: sh,          runbin: "./ags",      bindir: "",        cmakecmd: "cmake" }
        - { name: Emscripten,           os: ubuntu-latest,    sys: Web,     gfx: OGL,  artifact: 'ags-emscripten',   shell: sh,          runbin: "",           bindir: ""       , cmakecmd: "emcmake cmake" }

    steps:
    - name: Set up MSYS2
      if: matrix.platform.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.platform.msystem }}
        install: >-
          ${{ matrix.platform.msys-env }}-cc
          ${{ matrix.platform.msys-env }}-cmake
          ${{ matrix.platform.msys-env }}-ninja
          ${{ matrix.platform.msys-env }}-perl
          ${{ matrix.platform.msys-env }}-python-pip
          ${{ matrix.platform.msys-env }}-pkg-config
          ${{ matrix.platform.msys-env }}-clang-tools-extra
          unzip

    - name: Set up SDL dependencies on Linux (ensures OpenGL)
      if: matrix.platform.sys == 'Ubuntu'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev \
          libusb-1.0-0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev \
          libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

    - name: Set up Tappy
      run: pip install tap.py

    - uses: actions/checkout@v6

    - uses: mymindstorm/setup-emsdk@v16
      if: ${{ matrix.platform.name == 'Emscripten' }}
      with:
        version: 3.1.74

    - name: Configure CMake
      run: |
        cmake --version
        ${{ matrix.platform.cmakecmd }} -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DAGS_BUILD_TOOLS=1 -DAGS_TESTS=1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Test
      if: ${{ matrix.platform.name != 'Emscripten' }}
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.platform.artifact }}
        path: |
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/ags.exe
          ${{github.workspace}}/build/ags
          ${{github.workspace}}/build/ags.exe
          ${{github.workspace}}/build/ags.html
          ${{github.workspace}}/build/ags.wasm
          ${{github.workspace}}/build/ags.js

    - name: Download auto-test
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        curl -sLo auto-test.zip https://github.com/adventuregamestudio/ags-test-games/releases/latest/download/${{env.AUTO_TEST_ASSET_BASENAME}}.zip

    - name: Unzip auto-test
      if: matrix.platform.shell == 'cmd'
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        tar -f auto-test.zip -xvzC .
        del auto-test.

    - name: Unzip auto-test
      if: matrix.platform.shell != 'cmd'
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        unzip auto-test.zip
        rm auto-test.zip

    - name: Run auto-test (Hardware GFX)
      if: ${{ matrix.platform.name != 'Emscripten' }}
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        ${{matrix.platform.runbin}} --gfxdriver ${{matrix.platform.gfx}} --no-message-box --log-stdout=script:info,main:info --user-data-dir . ${{env.AUTO_TEST_ASSET_BASENAME}}.ags
        mv agstest.tap agstest_hardware.tap

    - name: Check auto-test (Hardware GFX) # we are using tap.py so that the pipeline fails if a test fails
      if: ${{ matrix.platform.name != 'Emscripten' }}
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        tappy agstest_hardware.tap

    - name: Run auto-test (Software GFX)
      if: ${{ matrix.platform.name != 'Emscripten' }}
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        ${{matrix.platform.runbin}} --gfxdriver Software --no-message-box --log-stdout=script:info,main:info --user-data-dir . ${{env.AUTO_TEST_ASSET_BASENAME}}.ags
        mv agstest.tap agstest_software.tap

    - name: Check auto-test (Software GFX) # we are using tap.py so that the pipeline fails if a test fails
      if: ${{ matrix.platform.name != 'Emscripten' }}
      working-directory: ${{github.workspace}}/build/${{matrix.platform.bindir}}
      run: |
        tappy agstest_software.tap


  build-android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
  
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Install bsdtar
        run: |
          sudo apt-get install -y libarchive-tools
  
      - name: Set up Android SDK
        run: |
          cd Android && ./and-download-sdk-tools.sh linux
          echo "${ANDROID_HOME}/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "${ANDROID_HOME}/platform-tools" >> "$GITHUB_PATH"
          echo "ANDROID_HOME=${ANDROID_HOME}" >> "$GITHUB_ENV"
          echo "ANDROID_SDK_ROOT=${ANDROID_HOME}" >> "$GITHUB_ENV"
  
      - name: Install Android NDK r25
        run: sdkmanager --install "ndk;25.2.9519653" "build-tools;34.0.0"
  
      - name: Cache Gradle dependencies
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
  
      - name: Prepare Android build
        run: cd Android && ./and-build.sh prepare
  
      - name: Build debug APK
        run: cd Android && ./and-build.sh build_debug
  
      - name: Build release APK
        run: cd Android && ./and-build.sh build_release
  
      - name: Rename APKs
        run: cd Android && ./and-build.sh archive_apks
  
      - name: Create project archive
        run: cd Android && ./and-build.sh archive_project
  
      - uses: actions/upload-artifact@v7
        with:
          name: android-apks
          path: AGS-*.apk
  
      - uses: actions/upload-artifact@v7
        with:
          name: android-project
          path: AGS-*-android-proj-*.zip


  windows-msvc-tests:
    name: Windows MSVC Tests
    runs-on: windows-latest
    timeout-minutes: 40
    env:
      AGS_LIBOGG_LIB:        C:\Lib\Xiph\x86
      AGS_LIBTHEORA_LIB:     C:\Lib\Xiph\x86
      AGS_LIBVORBIS_LIB:     C:\Lib\Xiph\x86
      AGS_SDL_INCLUDE:       C:\Lib\SDL2\include
      AGS_SDL_LIB:           C:\Lib\SDL2\lib\x86
      AGS_SDL_SOUND_INCLUDE: C:\Lib\SDL_sound\src
      AGS_SDL_SOUND_LIB:     C:\Lib\SDL_sound\lib\x86
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: microsoft/setup-msbuild@v3

      - name: Cache Windows build dependencies
        id: cache-win-deps
        uses: actions/cache@v5
        with:
          path: C:\Lib
          key: win-deps-${{ hashFiles('Windows/setup_ags_build_deps.bat') }}

      - name: Install Windows build dependencies
        if: steps.cache-win-deps.outputs.cache-hit != 'true'
        shell: cmd
        run: Windows\setup_ags_build_deps.bat

      - name: Build Compiler test runner (x86)
        shell: cmd
        run: |
          cd Solutions
          msbuild Compiler.Lib.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32 /maxcpucount /nologo

      - name: Run Compiler tests (x86)
        run: Solutions\.test\Release\Compiler.Lib.Test.exe

      - name: Build AGS test runners (x86)
        shell: cmd
        run: |
          cd Solutions
          msbuild Tests.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32 /maxcpucount /nologo

      - name: Run Common tests (x86)
        run: Solutions\.test\Release\Common.Lib.Test.exe

      - name: Run Engine tests (x86)
        run: Solutions\.test\Release\Engine.App.Test.exe

      - name: Run Tools tests (x86)
        run: Solutions\.test\Release\Tools.Test.exe

      - name: Clean up
        shell: cmd
        run: cd Solutions && rd /s /q .test

      - name: Build Compiler test runner (x64)
        shell: cmd
        run: |
          cd Solutions
          msbuild Compiler.Lib.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64 /maxcpucount /nologo

      - name: Run Compiler tests (x64)
        run: Solutions\.test\Release\Compiler.Lib.Test.exe

      - name: Build AGS test runners (x64)
        shell: cmd
        run: |
          cd Solutions
          msbuild Tests.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64 /maxcpucount /nologo

      - name: Run Common tests (x64)
        run: Solutions\.test\Release\Common.Lib.Test.exe

      - name: Run Engine tests (x64)
        run: Solutions\.test\Release\Engine.App.Test.exe

      - name: Run Tools tests (x64)
        run: Solutions\.test\Release\Tools.Test.exe


  windows-msvc-engine:
    name: Windows MSVC Engine
    runs-on: windows-latest
    timeout-minutes: 40
    env:
      AGS_LIBOGG_LIB:        C:\Lib\Xiph\x86
      AGS_LIBTHEORA_LIB:     C:\Lib\Xiph\x86
      AGS_LIBVORBIS_LIB:     C:\Lib\Xiph\x86
      AGS_SDL_INCLUDE:       C:\Lib\SDL2\include
      AGS_SDL_LIB:           C:\Lib\SDL2\lib\x86
      AGS_SDL_SOUND_INCLUDE: C:\Lib\SDL_sound\src
      AGS_SDL_SOUND_LIB:     C:\Lib\SDL_sound\lib\x86
    steps:
      - uses: actions/checkout@v6

      - uses: microsoft/setup-msbuild@v3

      - name: Cache Windows build dependencies
        id: cache-win-deps
        uses: actions/cache@v5
        with:
          path: C:\Lib
          key: win-deps-${{ hashFiles('Windows/setup_ags_build_deps.bat') }}

      - name: Install Windows build dependencies
        if: steps.cache-win-deps.outputs.cache-hit != 'true'
        shell: cmd
        run: Windows\setup_ags_build_deps.bat

      - name: Build Engine (x86 Debug)
        shell: cmd
        run: |
          cd Solutions
          msbuild Engine.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=Win32 /maxcpucount /nologo

      - name: Build Tools (x86 Debug)
        shell: cmd
        run: |
          cd Solutions
          msbuild Tools.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=x86 /maxcpucount /nologo

      - name: Build Engine (x86 Release)
        shell: cmd
        run: |
          cd Solutions
          msbuild Engine.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32 /maxcpucount /nologo

      - name: Build Tools (x86 Release)
        shell: cmd
        run: |
          cd Solutions
          msbuild Tools.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x86 /maxcpucount /nologo

      - name: Upload x86 Engine PDBs
        uses: actions/upload-artifact@v7
        with:
          name: windows-engine-pdb-x86
          include-hidden-files: true
          path: Solutions/.build/*/acwin.pdb

      - name: Delete x86 PDB / intermediate files
        shell: cmd
        run: |
          cd Solutions\.build
          del /s /q *.pdb *.map *.ilk *.iobj *.ipdb

      - name: Upload x86 binaries
        uses: actions/upload-artifact@v7
        with:
          name: windows-engine-binaries-x86
          include-hidden-files: true
          path: Solutions/.build/*/*

      - name: Delete Win32 build output
        shell: cmd
        run: cd Solutions && rd /s /q .build

      - name: Build Engine (x64 Release)
        shell: cmd
        run: |
          cd Solutions
          msbuild Engine.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64 /maxcpucount /nologo

      - name: Upload x64 Engine PDBs
        uses: actions/upload-artifact@v7
        with:
          name: windows-engine-pdb-x64
          include-hidden-files: true
          path: Solutions/.build/*/acwin.pdb

      - name: Delete x64 PDB / intermediate files
        shell: cmd
        run: |
          cd Solutions\.build
          del /s /q *.pdb *.map *.ilk *.iobj *.ipdb

      - name: Upload x64 binaries
        uses: actions/upload-artifact@v7
        with:
          name: windows-engine-binaries-x64
          include-hidden-files: true
          path: Solutions/.build/*/*

  windows-msvc-editor:
    name: Windows MSVC Editor
    runs-on: windows-latest
    timeout-minutes: 40
    env:
      AGS_LIBOGG_LIB:        C:\Lib\Xiph\x86
      AGS_LIBTHEORA_LIB:     C:\Lib\Xiph\x86
      AGS_LIBVORBIS_LIB:     C:\Lib\Xiph\x86
      AGS_SDL_INCLUDE:       C:\Lib\SDL2\include
      AGS_SDL_LIB:           C:\Lib\SDL2\lib\x86
      AGS_SDL_SOUND_INCLUDE: C:\Lib\SDL_sound\src
      AGS_SDL_SOUND_LIB:     C:\Lib\SDL_sound\lib\x86
    steps:
      - uses: actions/checkout@v6

      - uses: microsoft/setup-msbuild@v3

      - name: Cache Windows build dependencies
        id: cache-win-deps
        uses: actions/cache@v5
        with:
          path: C:\Lib
          key: win-deps-${{ hashFiles('Windows/setup_ags_build_deps.bat') }}

      - name: Install Windows build dependencies
        if: steps.cache-win-deps.outputs.cache-hit != 'true'
        shell: cmd
        run: Windows\setup_ags_build_deps.bat

      - name: Copy irrKlang DLLs to Editor\References
        shell: pwsh
        run: |
          Copy-Item C:\Lib\irrKlang\x86\*.dll Editor\References\
          New-Item -ItemType Directory -Path Editor\References\x64 -Force
          Copy-Item C:\Lib\irrKlang\x64\*.dll Editor\References\x64
      
      - name: Cache NuGet packages
        id: cache-nuget
        uses: actions/cache@v5
        with:
          path: Solutions\packages
          key: nuget-${{ hashFiles('Editor/AGS.Editor/packages.config', 'Editor/AGS.Types/packages.config', 'Editor/AGS.Editor.Tests/packages.config') }}

      - name: Restore NuGet packages
        if: steps.cache-nuget.outputs.cache-hit != 'true'
        shell: cmd
        run: nuget restore Solutions\AGS.Editor.Full.sln

      - name: Build Editor (Debug)
        shell: cmd
        run: |
          cd Solutions
          msbuild AGS.Editor.Full.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Debug /p:Platform=Win32 /maxcpucount /nologo

      - name: Run NUnit tests (Debug)
        shell: cmd
        run: |
          curl -fLOJ https://github.com/nunit/nunit-transforms/raw/master/nunit3-junit/nunit3-junit.xslt
          pushd Solutions\packages\NUnit.ConsoleRunner.3.*
          set RUNNER="%CD%\tools\nunit3-console.exe"
          popd
          cmd /v:on /c "!RUNNER! Editor\AGS.Editor.Tests\bin\Debug\AGS.Editor.Tests.dll --result=TestResult-junit.xml;transform=nunit3-junit.xslt"

      - name: Build Editor (Release)
        shell: cmd
        run: |
          cd Solutions
          msbuild AGS.Editor.Full.sln /m /p:MultiProcessorCompilation=true /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32 /maxcpucount /nologo

      - name: Run NUnit tests (Release)
        shell: cmd
        run: |
          curl -fLOJ https://github.com/nunit/nunit-transforms/raw/master/nunit3-junit/nunit3-junit.xslt
          pushd Solutions\packages\NUnit.ConsoleRunner.3.*
          set RUNNER="%CD%\tools\nunit3-console.exe"
          popd
          cmd /v:on /c "!RUNNER! Editor\AGS.Editor.Tests\bin\Release\AGS.Editor.Tests.dll --result=TestResult-junit.xml;transform=nunit3-junit.xslt"
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: editor-test-results
          include-hidden-files: true
          path: TestResult-junit.xml

      - name: Upload Editor PDBs
        uses: actions/upload-artifact@v7
        with:
          name: windows-editor-pdb
          include-hidden-files: true
          path: |
            Solutions/.build/*/*.pdb
            Editor/AGS.Native/*/AGS.Native.pdb

      - name: Delete Editor PDBs and XML docs
        shell: cmd
        run: |
          cd Solutions\.build
          del /s /q *.pdb *.xml

      - name: Upload Editor Release binaries
        uses: actions/upload-artifact@v7
        with:
          name: windows-editor-binaries
          include-hidden-files: true
          path: Solutions/.build/Release/*

  package-pdbs:
    name: PDB Packaging
    runs-on: ubuntu-latest
    needs:
      - windows-msvc-engine
      - windows-msvc-editor
    steps:
      - uses: actions/checkout@v6

      - name: Download Engine x86 PDBs
        uses: actions/download-artifact@v8
        with:
          name: windows-engine-pdb-x86
          path: pdbs/

      - name: Download Engine x64 PDBs
        uses: actions/download-artifact@v8
        with:
          name: windows-engine-pdb-x64
          path: pdbs/

      - name: Download Editor PDBs
        uses: actions/download-artifact@v8
        with:
          name: windows-editor-pdb
          path: pdbs/

      - name: Install bsdtar
        run: sudo apt-get install -y libarchive-tools

      - name: Create PDB archive
        run: |
          version=$(awk -F'[ "]+' '$1=="#define" && $2=="ACI_VERSION_STR" { print $3; exit }' Common/ac/def_version.h)
          bsdtar -f "AGS-${version}-pdb.zip" -acv pdbs/

      - name: Upload PDB archive
        uses: actions/upload-artifact@v7
        with:
          name: pdb-archive
          include-hidden-files: true
          path: AGS-*-pdb.zip


  windows-packaging:
    name: Windows Packaging
    runs-on: windows-latest
    timeout-minutes: 60
    needs:
      - windows-msvc-editor
      - windows-msvc-engine
    env:
      TEMPLATES_REPOSITORY: adventuregamestudio/ags-templates
      AGS_SDL_LIB: C:\Lib\SDL2\lib\x86
    steps:
      - uses: actions/checkout@v6


      - name: Cache Windows build dependencies
        id: cache-win-deps
        uses: actions/cache@v5
        with:
          path: C:\Lib
          key: win-deps-${{ hashFiles('Windows/setup_ags_build_deps.bat') }}

      - name: Setup msbuild if we need to build SDL_sound (For WinDevDependenciesVS)
        uses: microsoft/setup-msbuild@v3
        if: steps.cache-win-deps.outputs.cache-hit != 'true'

      - name: Install Windows build dependencies (For WinDevDependenciesVS)
        if: steps.cache-win-deps.outputs.cache-hit != 'true'
        shell: cmd
        run: Windows\setup_ags_build_deps.bat

      - name: Download Editor binaries
        uses: actions/download-artifact@v8
        with:
          name: windows-editor-binaries
          path: Windows\Installer\Source\Editor

      - name: Download Engine x86 binary
        uses: actions/download-artifact@v8
        with:
          name: windows-engine-binaries-x86
          path: Windows\Installer\Source\Engine_tmp

      - name: Copy acwin.exe and SDL2.dll
        shell: cmd
        run: |
          mkdir Windows\Installer\Source\Engine
          copy Windows\Installer\Source\Engine_tmp\Release\acwin.exe Windows\Installer\Source\Engine\acwin.exe
          copy %AGS_SDL_LIB%\SDL2.dll Windows\Installer\Source\Engine\SDL2.dll

      - name: Download AGS manual
        shell: cmd
        run: |
          mkdir Windows\Installer\Source\Docs
          cd Windows\Installer\Source\Docs
          curl -fLOJ https://github.com/adventuregamestudio/ags-manual/releases/latest/download/${{env.MANUAL_ASSET}}

      - name: Download AGS templates
        shell: cmd
        run: |
          mkdir Windows\Installer\Source\Templates
          curl -fLSs https://github.com/%TEMPLATES_REPOSITORY%/tarball/${{env.BASE_BRANCH}} | tar -f - -xvzC Windows\Installer\Source\Templates --strip-components 2

      - name: Build release archive
        shell: cmd
        run: |
          move Windows\Installer\Source\Docs\* Windows\Installer\Source\Editor\
          move Windows\Installer\Source\Engine\* Windows\Installer\Source\Editor\
          move Windows\Installer\Source\Licenses Windows\Installer\Source\Editor\
          move Windows\Installer\Source\Templates Windows\Installer\Source\Editor\
          move Windows\Installer\Source\URLs Windows\Installer\Source\Editor\
          tar -f AGS-Package.zip -acv --strip-components 4 Windows\Installer\Source\Editor

      - name: Upload release archive
        uses: actions/upload-artifact@v7
        with:
          name: windows-release-archive
          path: AGS-*.zip

      - name: Build WinDevDependenciesVS archive
        shell: cmd
        run: |
          pushd "C:\Lib\SDL_sound" && del /Q /S build_x86\* && rd /Q /S build_x86 && del /Q /S build_x64\* && rd /Q /S build_x64 && popd
          tar -f WinDevDependenciesVS.zip -acv --strip-components 2 C:\Lib

      - name: Upload WinDevDependenciesVS
        uses: actions/upload-artifact@v7
        with:
          name: windows-dev-dependencies
          path: WinDevDependenciesVS.zip
